import Head from 'next/head'
import { GetServerSideProps, GetStaticProps } from 'next/types'
import { HomeProps } from '../model/home-props';



export default function Home({ data }: HomeProps) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Test</h1>
      <ul>
        {
          data.map((item, index) => {
            return <li key={index}>{item.department_name}{item.id}</li>
          })
        }
      </ul>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const res = await fetch(`https://api.ikns.info/api/data/2009-2010`);
  const data = await res.json()
  return {
    props: {
      data
    }
  }
}

